# SITE CONFIGURATION
title: El Rustaceo
author: El Rustaceo # You :P
description: > # Meta description of Homepage
    Un blog de Rust en español, para aprender el lenguaje y sobre programación en general.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://elrustaceo.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: El Rustaceo 
  links:
    - https://twitter.com/elrustaceo
    - https://github.com/elrustaceo

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Links', link: '/links'}
  - {name: 'Acerca de', link: '/about'}
  - {name: 'Contacto', link: '/contacto'}

tagline: >
        Un blog sobre Rust y programación 

hero_img: bg.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: elrustaceo@gmail.com # email for form submission

twitter_username: elrustaceo # replace with your_twitter_username or comment to remove link from footer
github_username: elrustaceo # replace with your_github_username or comment to remove link from footer

#p disqus:
#  shortname: elrustaceo # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - old_posts
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
